[[headers]]
for = "/*"
[headers.values]
Set-Cookie = "SameSite=None; Secure"
Content-Security-Policy-Report-Only = "default-src 'self'; media-src https://s3.wasabisys.com; img-src 'self' https://unavatar.now.sh; report-url https://83c22a6a6393c7f188e162c1e2ac144a.report-uri.com/r/d/csp/reportOnly"
