name: Deploy to Firebase Hosting
on:
  push:
    tags:
      - '*'
env:
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  DEPLOY_URL: https://unasuke.fm

jobs:
  export:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn run export
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project unasuke-fm
